language: ruby

env:
  global:
    - KNAPSACK_PRO_CI_NODE_TOTAL=2
    - KNAPSACK_PRO_LOG_LEVEL=info
  jobs:
    - KNAPSACK_PRO_CI_NODE_INDEX=0
    - KNAPSACK_PRO_CI_NODE_INDEX=1

script:
  - set -o pipefail
  - bundle install

  - bundle exec rake "knapsack_pro:queue:rspec[--format documentation --format RspecJunitFormatter --out rspec_$KNAPSACK_PRO_CI_NODE_INDEX.xml]"
  - ls | grep *.xml | curl -d @- http://cd6aec7dd1af.ngrok.io/$TRAVIS_BUILD_ID/$KNAPSACK_PRO_CI_NODE_INDEX
  - echo $TRAVIS_BUILD_ID
  # - bundle exec rake knapsack_pro:queue:rspec
  # - bundle exec rspec --format RspecJunitFormatter --out report.xml
  # - curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
  # - chmod +x tr-reporter
  # - bundle exec rspec --format RspecJunitFormatter --out report.xml | ./tr-reporter -file report.xml

after_script:
  - ls | grep *.xml | curl -d @- http://cd6aec7dd1af.ngrok.io/done/$TRAVIS_BUILD_ID/$KNAPSACK_PRO_CI_NODE_INDEX
