language: ruby

env:
  global:
    - KNAPSACK_PRO_CI_NODE_TOTAL=2
    - KNAPSACK_PRO_LOG_LEVEL=info
    - RUN_ID=$(date +%s%N)
  jobs:
    - KNAPSACK_PRO_CI_NODE_INDEX=0
    - KNAPSACK_PRO_CI_NODE_INDEX=1

script:
  - set -o pipefail
  - bundle install

  - bundle exec rake "knapsack_pro:queue:rspec[--format documentation --format RspecJunitFormatter --out rspec_$KNAPSACK_PRO_CI_NODE_INDEX.xml]"
  - ls | curl -d @- http://bd10f3171262.ngrok.io/script/$RUN_ID
  - env | grep '^TRAVIS*=*'
  # - bundle exec rake knapsack_pro:queue:rspec
  # - bundle exec rspec --format RspecJunitFormatter --out report.xml
  # - curl -o tr-reporter https://downloads.testrecall.com/r/latest/reporter.linux-amd64
  # - chmod +x tr-reporter
  # - bundle exec rspec --format RspecJunitFormatter --out report.xml | ./tr-reporter -file report.xml

after_script:
  - ls | curl -d @- http://bd10f3171262.ngrok.io/done/$RUN_ID

jobs:
  include:
    - stage: Upload
      script: env | grep '^TRAVIS*=*' && ls | curl -d @- http://bd10f3171262.ngrok.io/upload/$RUN_ID
      after_script: ls | curl -d @- http://bd10f3171262.ngrok.io/upload_after/$RUN_ID
